config/routes.rb
Rails.application.routes.draw do
  resources :monitorings
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get :_healthz, to: ->(_req) {
    # 检查 redis
    Redis.current.get('healthz')
    # 检查数据库版本
    ActiveRecord::Migration.check_pending!
    [200, {}, ["OK\n"]]
  }

  mount API::Root => '/'
  mount GrapeSwaggerRails::Engine => '/api/tm-docs'
  root to:"main#index"
  
  get "display", to: "display#new"
  post "display", to: "display#show"
  get "index_display", to: "display#index"
  get "shows_display", to: "display#show"

  get "recei", to: "search#new"
#post "recei", to: "search#show"
get "show_search", to: "search#show"
post "show_search", to: "search#show"

get "show_monitorings", to: "monitorings#show"
post "show_monitorings", to: "monitorings#show"

get "test", to: "search#index"
 

  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/monitoring.rb
class Monitoring < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/display_controller.rb
class DisplayController < ApplicationController
before_action :get_num, :today, only: %i[index]

def new
    
end

def index
  
  
end

def  show
    
end

private

def get_num

    @displays = Monitoring.last(5)
    @display_all =Monitoring.all
end

def today

    @today_num = Monitoring.where(created_t: Time.now.midnight..(Time.now.midnight + 1.day))
end

end

app/controllers/main_controller.rb
class MainController < ApplicationController
end

app/controllers/monitorings_controller.rb
class MonitoringsController < ApplicationController
  before_action :set_monitoring, only: %i[ show edit update destroy ]

  # GET /monitorings or /monitorings.json
  def index
    @monitorings = Monitoring.all
  end

  # GET /monitorings/1 or /monitorings/1.json
  def show
   
  end

  # GET /monitorings/new
  def new
    @monitoring = Monitoring.new
  end

  # GET /monitorings/1/edit
  def edit
  end

  # POST /monitorings or /monitorings.json
  def create
    @monitoring = Monitoring.new(monitoring_params)

    respond_to do |format|
      if @monitoring.save
        format.html { redirect_to @monitoring, notice: "Monitoring was successfully created." }
        format.json { render :show, status: :created, location: @monitoring }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @monitoring.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /monitorings/1 or /monitorings/1.json
  def update
    respond_to do |format|
      if @monitoring.update(monitoring_params)
        format.html { redirect_to @monitoring, notice: "Monitoring was successfully updated." }
        format.json { render :show, status: :ok, location: @monitoring }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @monitoring.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /monitorings/1 or /monitorings/1.json
  def destroy
    @monitoring.destroy
    respond_to do |format|
      format.html { redirect_to monitorings_url, notice: "Monitoring was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_monitoring
      @monitoring = Monitoring.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def monitoring_params
      params.require(:monitoring).permit(:tenant_id, :receive_id, :receive_type, :kind, :title, :content, :event_id, :extra_data, :deleted_t, :created_t)
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
before_action :s_tenant, only: %i[show]
    def index
    end

    def show
      @searching = Monitoring.all
    end
    
    def new
    end



private

def s_tenant
    
    
 @searching = Monitoring.find_by(tenant_id: params[:tenant_id])
      
    

end

def fing_par
params.require(:search).permit(:receive_type)


end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/monitorings_helper.rb
module MonitoringsHelper
end

app/views/display/index.html.erb
<div class="jumbotron jumbotron-fluid">
    <div class="container">
      <h1 class="display-4">数据展示</h1>
      <p class="lead">最新的五条消息以及总发送量与今日发送量</p>
    </div>
  </div>
<tbody class="mb-3">
  <% @displays.each do |monitoring| %>
    <div class="list-group">
        <a href="#" class="list-group-item list-group-item-action flex-column align-items-start">
          <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1"><%= monitoring.title %></h5>
            <small class="text-muted"><%= monitoring.created_t.to_time.strftime('%B %e at %l:%M %p') %></small>
          </div>
          <p class="mb-1"><%= monitoring.content %></p>
          <small class="text-muted">Created By <%= monitoring.tenant_id %>.</small>
        </a>
       </div>
    </tbody>
  <% end %>

<div class="row justify-content-center">
    <div class="col-md-6 col-lg-3">
        <div class="card report-card">
            <div class="card-body">
                <div class="row d-flex justify-content-center">
                    <div class="col">
                        <p class="text-dark mb-0 font-weight-semibold">发送总量</p>
                        <h3 class="m-0">
                            <%= @display_all.size %>
                        </h3>
                        <p class="mb-0 text-truncate text-muted"><span class="text-success"><i class="mdi mdi-trending-up"></i>8.5%</span> New Sessions Today</p>
                    </div>
                    <div class="col-auto align-self-center">
                        <div class="report-main-icon bg-light-alt">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-users align-self-center text-muted icon-sm"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path><circle cx="9" cy="7" r="4"></circle><path d="M23 21v-2a4 4 0 0 0-3-3.87"></path><path d="M16 3.13a4 4 0 0 1 0 7.75"></path></svg>  
                        </div>
                    </div>
                </div>
            </div><!--end card-body--> 
        </div><!--end card--> 
    </div> <!--end col--> 
    
        <div class="col-md-6 col-lg-3">
            <div class="card report-card">
                <div class="card-body">
                    <div class="row d-flex justify-content-center">
                        <div class="col">
                            <p class="text-dark mb-0 font-weight-semibold">今日发送量</p>
                            <h3 class="m-0">
                                <%= @today_num.size %>
                            </h3>
                            <p class="mb-0 text-truncate text-muted"><span class="text-success"><i class="mdi mdi-trending-up"></i>8.5%</span> New Sessions Today</p>
                        </div>
                        <div class="col-auto align-self-center">
                            <div class="report-main-icon bg-light-alt">
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-users align-self-center text-muted icon-sm"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path><circle cx="9" cy="7" r="4"></circle><path d="M23 21v-2a4 4 0 0 0-3-3.87"></path><path d="M16 3.13a4 4 0 0 1 0 7.75"></path></svg>  
                            </div>
                        </div>
                    </div>
                </div><!--end card-body--> 
            </div><!--end card--> 
        </div> <!--end col--> 
    <div style="height: 200px;"></div>
    

    </div>
    <canvas id="myChart"></canvas>
    <script>
    var ctx = document.getElementById('myChart').getContext('2d');
    var chart = new Chart(ctx, {
        // 要创建的图表类型
        type: 'line',
    
        // 数据集
        data: {
            labels: ["January", "February", "March", "April", "May", "June", "July"],
            datasets: [{
                label: "My First dataset",
                backgroundColor: 'rgb(255, 99, 132)',
                borderColor: 'rgb(255, 99, 132)',
                data: [0, 11, 10, 2, 20, 30, 45],
            }]
        },
    
        // 配置选项
        options: {}
    });
    </script>
    <%= link_to "chart", shows_display_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Messaging</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.4.0/Chart.min.js"></script>


    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "shared/navbar" %>
    <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/main/index.html.erb
<div class="jumbotron">
    <h1 class="display-3">Messaging</h1>
    <p class="lead">This is a simple messaging managment, available for searching information.</p>
    <hr class="my-4">
    <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
    <p class="lead">
      <%= link_to "Get Start", new_monitoring_path, class:"btn btn-primary btn-lg" %>
    </p>
  </div>

app/views/monitorings/_form.html.erb
<%= form_with(model: monitoring, local: true) do |form| %>
  <% if monitoring.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(monitoring.errors.count, "error") %> prohibited this monitoring from being saved:</h2>

      <ul>
        <% monitoring.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  


<form>
  <div class="row justify-content-center">
    <div class="form-group col-md-6">
      <label for="inputEmail4">TenantID</label>
      <%= form.number_field :tenant_id, class:"form-control", id:"inputEmail4", placeholder:"email" %>
    </div>
    <div class="form-group col-md-6">
      <label for="inputPassword4">ReceiveID</label>
      <%= form.text_field :receive_id,class:"form-control", id:"inputPassword4", placeholder:"Receiver" %>
    </div>
    <div class="form-group col-md-6">
      <label for="inputPassword4">ReceiveTYPE</label>
      <%= form.text_field :receive_type,class:"form-control", id:"inputPassword4", placeholder:"typeNum" %>
    </div>
    <div class="form-group col-md-6">
      <label for="inputPassword4">Kind</label>
      <%= form.number_field :kind,class:"form-control", id:"inputPassword4", placeholder:"kindNum" %>
    </div>
  </div>

  <div class="form-group">
    <label for="inputAddress">Title</label>
    <%= form.text_field :title,class:"form-control", id:"inputPassword4", placeholder:"Title" %>
  </div>
  <div class="form-group card-body">
    <label for="inputAddress2">Content</label>
    <%= form.text_field :content,class:"form-control", id:"inputPassword4", placeholder:"typeNum" %>
  </div>
  <div class="row justify-content-center">
    <div class="form-group col-md-2">
      <label for="inputCity">EventID</label>
      <%= form.number_field :event_id,class:"form-control", id:"inputPassword4", placeholder:"eventNum" %>
    </div>
    <div class="form-group col-md-2">
      <label for="inputState">extraData</label>
      <%= form.text_field :extra_data,class:"form-control", id:"inputPassword4", placeholder:"Data" %>
    </div>
    
      <div class="field form-group">
        <%= form.label :deleted_t %>
        <%= form.datetime_select :deleted_t %>
      </div>
    
      
    
    <div class="field form-group">
      <%= form.label :created_t %>
      <%= form.datetime_select :created_t %>
    </div>
  </div>
  <div class="actions">
    <%= form.submit class:"btn btn-primary" %>
  </div>

</form>
<% end %>

app/views/monitorings/edit.html.erb
<h1>Editing Monitoring</h1>

<%= render 'form', monitoring: @monitoring %>

<%= link_to 'Show', @monitoring, class:"btn btn-outline-primary" %> 
<%= link_to 'Back', monitorings_path, class:"btn btn-outline-primary" %>

app/views/monitorings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Monitorings</h1>

<table>
  <thead>
    <tr>
      <th>Tenant</th>
      <th>Receive</th>
      <th>Receive type</th>
      <th>Kind</th>
      <th>Title</th>
      <% if false %>
      <th>Content</th>
      <% end %>
      <th>Event</th>
      <th>Extra data</th>
      <th>Deleted t</th>
      <th>Created t</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @monitorings.each do |monitoring| %>
      <tr>
        <td><%= monitoring.tenant_id %></td>
        <td><%= monitoring.receive_id %></td>
        <td><%= monitoring.receive_type %></td>
        <td><%= monitoring.kind %></td>
        <td><%= monitoring.title %></td>
        <% if false %>
        <td><%= monitoring.content %></td>
        <% end %>
        <td><%= monitoring.event_id %></td>
        <td><%= monitoring.extra_data %></td>
        <td><%= monitoring.deleted_t.to_time.strftime('%B %e at %l:%M %p') %></td>
        <td><%= monitoring.created_t.to_time.strftime('%B %e at %l:%M %p') %></td>
        <td><%= link_to 'show', monitoring, class:"btn btn-outline-secondary" %></td>
        <td><%= link_to 'Edit', edit_monitoring_path(monitoring), class:"btn btn-outline-secondary" %></td>
        <td><%= link_to 'Destroy', monitoring, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-outline-secondary" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Monitoring', new_monitoring_path, class: "btn btn-outline-primary"%>

app/views/monitorings/new.html.erb
<h1>New Monitoring</h1>

<%= render 'form', monitoring: @monitoring %>

<%= link_to 'Back', monitorings_path,class:"btn btn-outline-primary" %>

app/views/monitorings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tenant:</strong>
  <%= @monitoring.tenant_id %>
</p>

<p>
  <strong>Receive:</strong>
  <%= @monitoring.receive_id %>
</p>

<p>
  <strong>Receive type:</strong>
  <%= @monitoring.receive_type %>
</p>

<p>
  <strong>Kind:</strong>
  <%= @monitoring.kind %>
</p>

<p>
  <strong>Title:</strong>
  <%= @monitoring.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @monitoring.content %>
</p>

<p>
  <strong>Event:</strong>
  <%= @monitoring.event_id %>
</p>

<p>
  <strong>Extra data:</strong>
  <%= @monitoring.extra_data %>
</p>

<p>
  <strong>Deleted t:</strong>
  <%= @monitoring.deleted_t %>
</p>

<p>
  <strong>Created t:</strong>
  <%= @monitoring.created_t %>
</p>

<%= link_to 'Edit', edit_monitoring_path(@monitoring),class:"btn btn-outline-primary" %> |
<%= link_to 'Back', monitorings_path,class:"btn btn-outline-primary" %>
<%= button_to('To Dispaly',show_search_path,method: :get,params:{tenant_id: @monitoring.tenant_id}, class:"btn btn-success")%>

app/views/search/new.html.erb
<h1>Messages Searching</h1>
<%= form_for :search, remote: false, url: show_search_path do |form| %>

 <div class="mb-3">
    <%= form.label :tenant_id %>
   <%= form.text_field :tenant_id, class: "form-control", placeholder: "UserID" %>
  </div>

  <div class="mb-3">
    <%= form.submit "search", class: "btn btn-primary"%>
  </div> 
  
  
<% end %>

<%= form_for :search2, remote: false, url: show_search_path do |form| %>

 <div class="mb-3">
    <%= form.label "Created At" %>
   <%= form.date_select :created_t, class: "form-control", placeholder: "UserID" %>
  </div>

  <div class="mb-3">
    <%= form.submit "search", class: "btn btn-primary"%>
  </div> 
  
  
<% end %>

<%= button_to "click", show_search_path %>

app/views/search/show.html.erb
<h1>This is your messages</h1>
<div class="mb-3">
 
    <% @searching.where(tenant_id: params.dig(:search, :tenant_id)).each do |monitoring| %> 
    
        <div class=card>
            <div class="card-header">
              Created By <%= monitoring.tenant_id %>
            </div>
            <div class="card-body">
              <blockquote class="blockquote mb-0">
                <p><%= monitoring.title%><%= button_to('Details',show_monitorings_path,method: :get,params:{id: monitoring.id}, class:"btn btn-outline-danger")%></p>
                
                <footer class="blockquote-footer">Created at  <%= monitoring.created_t.to_time.strftime('%B %e at %l:%M %p') %><cite title="Source Title"></cite></footer>
              </blockquote>
            </div>
          
          
   </div>
    <% end %>

    <% @searching.where("created_at >= ? and created_at <=?", :search2.to_time,:search2.to_time).each do |monitoring| %> 
    
        <div class="card">
            <div class="card-header">
              Created By <%= monitoring.tenant_id %>
            </div>
            <div class="card-body">
              <blockquote class="blockquote mb-0">
                <p><%= monitoring.title%><%= button_to('Details',show_monitorings_path,method: :get,params:{id: monitoring.id},class:"btn btn-outline-secondary") %></p>
                
                <footer class="blockquote-footer"><cite title="Source Title"></cite>Created at  <%= monitoring.created_t.to_time.strftime('%B %e at %l:%M %p') %></cite></footer>
              </blockquote>
            </div>
        </div>
          
   
    <% end %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark" style="background-color:#20c997;">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">Messaging managment</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <%= link_to "Send",monitorings_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Display",index_display_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Search",recei_path, class: "nav-link" %>
          </li>

        </ul>
        
        

       
      </div>
    </div>
  </nav>